### ISSUE TITLE
FastNoise2 submodule not installing

### ISSUE THREAD

**Issue by connorjak** [caseymcc/UE4_FastNoise2#2]
The FastNoise2 submodule seems to be missing on both the GitHub browsing of the repo and when cloning. Manually cloning FastNoise2 makes the rest of the process work fine.

As a side note, the errors I was having were during the `Generate VS Project FIles` command from right clicking the .uproject, which auto-closes when complete. The cmake errors were both not being printed to the UE4 saved logfile and the window was auto-exiting within a second of the errors appearing. I had to quickly select and copy the text to read the errors.

**Comment by caseymcc** [comment]
Hopefully this: https://github.com/caseymcc/UE4_FastNoise2/commit/70a00728952dc26f09f77b4cd311ba2a978c4a39 will fix the submodule. I will see about how to add the cmake errors to the ue4 log.

**Comment by connorjak** [comment]
Yes the submodule is fixed now. Thanks!
